apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  vite-api-url: 'http://ecommerce-app:8080/api/v1'
  environment: 'production'
  http-port: '8080'
  minio-endpoint: 'ecommerce.minio:9000'
  minio-bucket: 'ecommerce'
  minio-baseurl: 'http://localhost:9000' # Lưu ý: localhost có thể không đúng trong K8s, cân nhắc dùng tên service
  minio-usessl: 'false'
  redis-db: '1'
  mail-port: '587'
  mail-host: 'smtp.gmail.com'
  mail-from: 'anhquoc18092003@gmail.com'
